[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[build.ignore]
  ignore = "sanity-studio/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
